// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("b2");

/**
 * B2 Application Key (B2_APPLICATION_KEY env).
 */
export declare const applicationKey: string | undefined;
Object.defineProperty(exports, "applicationKey", {
    get() {
        return __config.get("applicationKey");
    },
    enumerable: true,
});

/**
 * B2 Application Key ID (B2_APPLICATION_KEY_ID env).
 */
export declare const applicationKeyId: string | undefined;
Object.defineProperty(exports, "applicationKeyId", {
    get() {
        return __config.get("applicationKeyId");
    },
    enumerable: true,
});

/**
 * B2 endpoint - the string 'production' or a custom B2 API URL (B2_ENDPOINT env). You should not need to set this unless
 * you work at Backblaze. Defaults to `production`.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

