// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getApplicationKey(args: GetApplicationKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetApplicationKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("b2:index/getApplicationKey:getApplicationKey", {
        "id": args.id,
        "keyName": args.keyName,
        "namePrefix": args.namePrefix,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApplicationKey.
 */
export interface GetApplicationKeyArgs {
    id?: string;
    keyName: string;
    namePrefix?: string;
}

/**
 * A collection of values returned by getApplicationKey.
 */
export interface GetApplicationKeyResult {
    readonly applicationKeyId: string;
    readonly bucketId: string;
    readonly capabilities: string[];
    readonly id: string;
    readonly keyName: string;
    readonly namePrefix: string;
    readonly options: string[];
}
export function getApplicationKeyOutput(args: GetApplicationKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetApplicationKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("b2:index/getApplicationKey:getApplicationKey", {
        "id": args.id,
        "keyName": args.keyName,
        "namePrefix": args.namePrefix,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApplicationKey.
 */
export interface GetApplicationKeyOutputArgs {
    id?: pulumi.Input<string>;
    keyName: pulumi.Input<string>;
    namePrefix?: pulumi.Input<string>;
}
