// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Check extends pulumi.CustomResource {
    /**
     * Get an existing Check resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CheckState, opts?: pulumi.CustomResourceOptions): Check {
        return new Check(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'healthchecksio:index/check:Check';

    /**
     * Returns true if the given object is an instance of Check.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Check {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Check.__pulumiType;
    }

    /**
     * Channels integrated with the check
     */
    declare public readonly channels: pulumi.Output<string[] | undefined>;
    declare public readonly checkId: pulumi.Output<string>;
    /**
     * Description of the check
     */
    declare public readonly desc: pulumi.Output<string | undefined>;
    /**
     * Grace period for the check
     */
    declare public readonly grace: pulumi.Output<number | undefined>;
    /**
     * Allowed HTTP methods for making ping requests
     */
    declare public readonly methods: pulumi.Output<string | undefined>;
    /**
     * Name of the check
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Pause URL associated with this check
     */
    declare public /*out*/ readonly pauseUrl: pulumi.Output<string>;
    /**
     * Ping URL associated with this check
     */
    declare public /*out*/ readonly pingUrl: pulumi.Output<string>;
    /**
     * A cron expression defining the check's schedule
     */
    declare public readonly schedule: pulumi.Output<string | undefined>;
    /**
     * Slug of the check
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * Tags associated with the check
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * Timeout period of the check
     */
    declare public readonly timeout: pulumi.Output<number | undefined>;
    /**
     * Timezone used for the schedule
     */
    declare public readonly timezone: pulumi.Output<string | undefined>;

    /**
     * Create a Check resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CheckArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CheckArgs | CheckState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CheckState | undefined;
            resourceInputs["channels"] = state?.channels;
            resourceInputs["checkId"] = state?.checkId;
            resourceInputs["desc"] = state?.desc;
            resourceInputs["grace"] = state?.grace;
            resourceInputs["methods"] = state?.methods;
            resourceInputs["name"] = state?.name;
            resourceInputs["pauseUrl"] = state?.pauseUrl;
            resourceInputs["pingUrl"] = state?.pingUrl;
            resourceInputs["schedule"] = state?.schedule;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["timeout"] = state?.timeout;
            resourceInputs["timezone"] = state?.timezone;
        } else {
            const args = argsOrState as CheckArgs | undefined;
            resourceInputs["channels"] = args?.channels;
            resourceInputs["checkId"] = args?.checkId;
            resourceInputs["desc"] = args?.desc;
            resourceInputs["grace"] = args?.grace;
            resourceInputs["methods"] = args?.methods;
            resourceInputs["name"] = args?.name;
            resourceInputs["schedule"] = args?.schedule;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeout"] = args?.timeout;
            resourceInputs["timezone"] = args?.timezone;
            resourceInputs["pauseUrl"] = undefined /*out*/;
            resourceInputs["pingUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Check.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Check resources.
 */
export interface CheckState {
    /**
     * Channels integrated with the check
     */
    channels?: pulumi.Input<pulumi.Input<string>[]>;
    checkId?: pulumi.Input<string>;
    /**
     * Description of the check
     */
    desc?: pulumi.Input<string>;
    /**
     * Grace period for the check
     */
    grace?: pulumi.Input<number>;
    /**
     * Allowed HTTP methods for making ping requests
     */
    methods?: pulumi.Input<string>;
    /**
     * Name of the check
     */
    name?: pulumi.Input<string>;
    /**
     * Pause URL associated with this check
     */
    pauseUrl?: pulumi.Input<string>;
    /**
     * Ping URL associated with this check
     */
    pingUrl?: pulumi.Input<string>;
    /**
     * A cron expression defining the check's schedule
     */
    schedule?: pulumi.Input<string>;
    /**
     * Slug of the check
     */
    slug?: pulumi.Input<string>;
    /**
     * Tags associated with the check
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Timeout period of the check
     */
    timeout?: pulumi.Input<number>;
    /**
     * Timezone used for the schedule
     */
    timezone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Check resource.
 */
export interface CheckArgs {
    /**
     * Channels integrated with the check
     */
    channels?: pulumi.Input<pulumi.Input<string>[]>;
    checkId?: pulumi.Input<string>;
    /**
     * Description of the check
     */
    desc?: pulumi.Input<string>;
    /**
     * Grace period for the check
     */
    grace?: pulumi.Input<number>;
    /**
     * Allowed HTTP methods for making ping requests
     */
    methods?: pulumi.Input<string>;
    /**
     * Name of the check
     */
    name?: pulumi.Input<string>;
    /**
     * A cron expression defining the check's schedule
     */
    schedule?: pulumi.Input<string>;
    /**
     * Slug of the check
     */
    slug?: pulumi.Input<string>;
    /**
     * Tags associated with the check
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Timeout period of the check
     */
    timeout?: pulumi.Input<number>;
    /**
     * Timezone used for the schedule
     */
    timezone?: pulumi.Input<string>;
}
