// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getChannel(args: GetChannelArgs, opts?: pulumi.InvokeOptions): Promise<GetChannelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("healthchecksio:index/getChannel:getChannel", {
        "kind": args.kind,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getChannel.
 */
export interface GetChannelArgs {
    kind: string;
    name?: string;
}

/**
 * A collection of values returned by getChannel.
 */
export interface GetChannelResult {
    readonly id: string;
    readonly kind: string;
    readonly name?: string;
}
export function getChannelOutput(args: GetChannelOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetChannelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("healthchecksio:index/getChannel:getChannel", {
        "kind": args.kind,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getChannel.
 */
export interface GetChannelOutputArgs {
    kind: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
