// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBucketFileSignedUrl(args: GetBucketFileSignedUrlArgs, opts?: pulumi.InvokeOptions): Promise<GetBucketFileSignedUrlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("b2:index/getBucketFileSignedUrl:getBucketFileSignedUrl", {
        "bucketId": args.bucketId,
        "duration": args.duration,
        "fileName": args.fileName,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBucketFileSignedUrl.
 */
export interface GetBucketFileSignedUrlArgs {
    bucketId: string;
    duration?: number;
    fileName: string;
    id?: string;
}

/**
 * A collection of values returned by getBucketFileSignedUrl.
 */
export interface GetBucketFileSignedUrlResult {
    readonly bucketId: string;
    readonly duration?: number;
    readonly fileName: string;
    readonly id: string;
    readonly signedUrl: string;
}
export function getBucketFileSignedUrlOutput(args: GetBucketFileSignedUrlOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBucketFileSignedUrlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("b2:index/getBucketFileSignedUrl:getBucketFileSignedUrl", {
        "bucketId": args.bucketId,
        "duration": args.duration,
        "fileName": args.fileName,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBucketFileSignedUrl.
 */
export interface GetBucketFileSignedUrlOutputArgs {
    bucketId: pulumi.Input<string>;
    duration?: pulumi.Input<number>;
    fileName: pulumi.Input<string>;
    id?: pulumi.Input<string>;
}
