// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the b2 package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'b2';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * B2 Application Key (B2_APPLICATION_KEY env).
     */
    declare public readonly applicationKey: pulumi.Output<string | undefined>;
    /**
     * B2 Application Key ID (B2_APPLICATION_KEY_ID env).
     */
    declare public readonly applicationKeyId: pulumi.Output<string | undefined>;
    /**
     * B2 endpoint - the string 'production' or a custom B2 API URL (B2_ENDPOINT env). You should not need to set this unless
     * you work at Backblaze. Defaults to `production`.
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["applicationKey"] = args?.applicationKey ? pulumi.secret(args.applicationKey) : undefined;
            resourceInputs["applicationKeyId"] = args?.applicationKeyId ? pulumi.secret(args.applicationKeyId) : undefined;
            resourceInputs["endpoint"] = args?.endpoint;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["applicationKey", "applicationKeyId"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * B2 Application Key (B2_APPLICATION_KEY env).
     */
    applicationKey?: pulumi.Input<string>;
    /**
     * B2 Application Key ID (B2_APPLICATION_KEY_ID env).
     */
    applicationKeyId?: pulumi.Input<string>;
    /**
     * B2 endpoint - the string 'production' or a custom B2 API URL (B2_ENDPOINT env). You should not need to set this unless
     * you work at Backblaze. Defaults to `production`.
     */
    endpoint?: pulumi.Input<string>;
}
